DEFAULT_URL_HOST: "localhost"
SWEET_INTEGRATOR_CONNECTION_TOKEN: 'sweet_token'
SWEET_INTEGRATOR_CONNECTION_ENPOINT: 'http://localhost:9292/cangaroo_connections'
CANGAROO_ENDPOINT: 'http://localhost:9292/cangaroo'
CANGAROO_SECRET_TOKEN: 'secrettoken'
CANGAROO_SECRET_KEY: 'secretkey'
SWEET_INTEGRATOR_SHOPIFY_KEY: 'secretkey'
SWEET_INTEGRATOR_SHOPIFY_TOKEN: 'secrettoken'
SWEET_INTEGRATOR_SHOPIFY_ENDPOINT: 'http://localhost:9292/shopify'
SWEET_INTEGRATOR_SHIPPING_EASY_KEY: 'secretkey'
SWEET_INTEGRATOR_SHIPPING_EASY_TOKEN: 'secrettoken'
SWEET_INTEGRATOR_SHIPPING_EASY_ENDPOINT: 'http://localhost:9292/shipping_easy'
