# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb06450201639b02d139b08018cc79d1daa66a818a4aed2f69a1513abe44669fe1d27998054f95f011be95dd40e01862d3feeb3c5860b47bd218ade079774d1f
  qbo_app_token: 347d7ac2b37aab4edeba4c3bddcd1396a51d
  qbo_oauth_consumer_key: qyprdOucNwZgapthVzzFt7XxLc9XrH
  qbo_oauth_consumer_secret: ASMW1kbAZJ21loREWKX16eFwDuClW6hp1hNmnQXM

test:
  secret_key_base: feb917a05fff6c2bd8aa8772730dc4a43b34b22b02dc6a226d6dc96ea3fe00f7123e865e02616e1a51c61e36da89164283bd0c00eae202afa0c990dfad0984f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
heroku_dev:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  qbo_app_token: <%= ENV["QBO_APP_TOKEN"] %>
  qbo_oauth_consumer_key: <%= ENV["QBO_OAUTH_CONSUMER_KEY"] %>
  qbo_oauth_consumer_secret: <%= ENV["QBO_OAUTH_CONSUMER_SECRET"] %>

demo:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  qbo_app_token: <%= ENV["QBO_APP_TOKEN"] %>
  qbo_oauth_consumer_key: <%= ENV["QBO_OAUTH_CONSUMER_KEY"] %>
  qbo_oauth_consumer_secret: <%= ENV["QBO_OAUTH_CONSUMER_SECRET"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  qbo_app_token: <%= ENV["QBO_APP_TOKEN"] %>
  qbo_oauth_consumer_key: <%= ENV["QBO_OAUTH_CONSUMER_KEY"] %>
  qbo_oauth_consumer_secret: <%= ENV["QBO_OAUTH_CONSUMER_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  qbo_app_token: <%= ENV["QBO_APP_TOKEN"] %>
  qbo_oauth_consumer_key: <%= ENV["QBO_OAUTH_CONSUMER_KEY"] %>
  qbo_oauth_consumer_secret: <%= ENV["QBO_OAUTH_CONSUMER_SECRET"] %>
